### ISSUE TITLE
False positives on AV scan

### ISSUE THREAD

**Issue by kierenhyl** [NAVCoin/navcoin-core#316] opened 2018-10-26 03:53 UTC
The NavCoin wallet is triggering some virus scanners - which doesn't make people feel secure about using the software.

Virus Detection - You can see which virus programs are detecting which issues here:
https://www.virustotal.com/#/file/d9fd992ed24edd1e3d4b7abe745fb647f221a684f148de34b49b4c68e063db0d/detection

This shows the following engines as triggering:
- MacOS:BitCoinMiner-BT [PUP]
- PUA.MAC.Miner
- BitCoinMiner (PUA)

Potential solutions:
- Signature obfuscation (finding what's triggering, and make slight changes to stop this)
- Report the false positives to the Antivirus vendors
- Digitally sign the application

**Comment by jims** [comment] 2018-11-14 10:16
Windows Defender is now also triggering a detection as `Trojan:Win32/Tiggre!plock`. So it is no longer possible to download on windows.

**Comment by howdystranger** [comment] 2019-02-06 07:50
I think since 4.5.1. it is no longer triggering Mozilla Firefox's inbuilt scanning for viruses - maybe the issue is resolved?

**Comment by aguycalled** [comment] 2019-02-06 09:29
closing

**Closed by aguycalled** 2019-02-06 09:29 UTC
Labels: bug, wallet

**Comment by howdystranger** [comment] 2019-02-13 18:22
Sorry to raise this again but I just saw on the #navcoin-support channel on Discord:
"When I attempted to update NAV Core Wallet from 4.5.1 to 4.5.2. The Avast antivirus would not allow because of some possible malware? Can you provide assistance. Thanks."
