### ISSUE TITLE
Display issue on Lenovo Yoga 920 low-res

### ISSUE THREAD

**Issue by IfaqYurmama** [navcoin/navcoin-core#223] opened 2018-06-12 21:05 UTC
Lenovo Yoga 920

![grafik](https://user-images.githubusercontent.com/33290035/41317177-bbf37d04-6e94-11e8-94b0-757efe153b6d.png)

--- Not my own issue, taken from [reddit](https://www.reddit.com/r/NavCoin/comments/8qj3sc/navcoin_wallet_v421_home_screen_looks_off_on_my/)  ---

**Comment by skillnwits** [comment] 2018-06-12 21:29
The older wallet version did not have that issue. The resolution on my Lenovo Yoga 920 laptop is 3840X2160.

**Comment by IfaqYurmama** [comment] 2018-06-12 21:48
From the screenshot it looks like you're using scale-up. What percentage is
that set at?

**Comment by skillnwits** [comment] 2018-06-13 11:22
I'm using 300%, but the previous wallet version did NOT require me to change my display settings.
![display](https://user-images.githubusercontent.com/40217613/41348396-154fb1dc-6ed2-11e8-8811-701adcbd5038.PNG)

**Comment by red010b37** [comment] 2018-06-20 08:46
Thanks for the info we will take a look

**Comment by aguycalled** [comment] 2018-12-11 22:35
@IfaqYurmama does 4.5.0 solve this?

**Comment by IfaqYurmama** [comment] 2018-12-12 03:57
@aguycalled I only opened it for a guy on reddit who since deleted his account. Maybe @skillnwits can confirm.

**Comment by skillnwits** [comment] 2018-12-14 23:43
Im on vacation and will get back on Monday.  I will let you know.
Thanks
________________________________

**Comment by mxaddict** [comment] 2019-07-15 15:32
Closing as this is a duplicate of #252

**Closed by mxaddict** 2019-07-15 15:32 UTC
Labels: gui
